redis:
  image: redis
  hostname: redis
  domainname: localdomain

snapshotservice:
  build: sdh-widget-snapshot-service
  hostname: snapshotservice
  domainname: localdomain
  links:
    - redis:redis
  environment:
    - TERM=xterm
    - PORT=8888
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - PHANTOM_WORKERS=1
    - PHANTOM_EXECUTORS_PER_WORKER=1
    - PERSISTENCE_DIRECTORY=/home/persisted/
    - API_URL
  ports:
    - 8888:8888